// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: telemetry.proto

package telemetrypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	TelemetryService_IngestTelemetry_FullMethodName     = "/telemetry.TelemetryService/IngestTelemetry"
	TelemetryService_GetTelemetryHistory_FullMethodName = "/telemetry.TelemetryService/GetTelemetryHistory"
)

// TelemetryServiceClient is the client API for TelemetryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TelemetryServiceClient interface {
	// IngestTelemetry is a client-streaming RPC: a satellite (or ground
	// station relay) opens one long-lived stream and pushes many readings
	// over it, instead of paying a connection setup cost per reading.
	// The server acks once, at the end, with a summary.
	IngestTelemetry(ctx context.Context, opts ...grpc.CallOption) (TelemetryService_IngestTelemetryClient, error)
	// GetTelemetryHistory is a plain unary RPC used by the dashboard/API
	// to pull back recent readings for one satellite.
	GetTelemetryHistory(ctx context.Context, in *TelemetryHistoryRequest, opts ...grpc.CallOption) (*TelemetryHistoryResponse, error)
}

type telemetryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTelemetryServiceClient(cc grpc.ClientConnInterface) TelemetryServiceClient {
	return &telemetryServiceClient{cc}
}

func (c *telemetryServiceClient) IngestTelemetry(ctx context.Context, opts ...grpc.CallOption) (TelemetryService_IngestTelemetryClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TelemetryService_ServiceDesc.Streams[0], TelemetryService_IngestTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &telemetryServiceIngestTelemetryClient{ClientStream: stream}
	return x, nil
}

type TelemetryService_IngestTelemetryClient interface {
	Send(*TelemetryReading) error
	CloseAndRecv() (*IngestSummary, error)
	grpc.ClientStream
}

type telemetryServiceIngestTelemetryClient struct {
	grpc.ClientStream
}

func (x *telemetryServiceIngestTelemetryClient) Send(m *TelemetryReading) error {
	return x.ClientStream.SendMsg(m)
}

func (x *telemetryServiceIngestTelemetryClient) CloseAndRecv() (*IngestSummary, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(IngestSummary)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *telemetryServiceClient) GetTelemetryHistory(ctx context.Context, in *TelemetryHistoryRequest, opts ...grpc.CallOption) (*TelemetryHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TelemetryHistoryResponse)
	err := c.cc.Invoke(ctx, TelemetryService_GetTelemetryHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TelemetryServiceServer is the server API for TelemetryService service.
// All implementations must embed UnimplementedTelemetryServiceServer
// for forward compatibility
type TelemetryServiceServer interface {
	// IngestTelemetry is a client-streaming RPC: a satellite (or ground
	// station relay) opens one long-lived stream and pushes many readings
	// over it, instead of paying a connection setup cost per reading.
	// The server acks once, at the end, with a summary.
	IngestTelemetry(TelemetryService_IngestTelemetryServer) error
	// GetTelemetryHistory is a plain unary RPC used by the dashboard/API
	// to pull back recent readings for one satellite.
	GetTelemetryHistory(context.Context, *TelemetryHistoryRequest) (*TelemetryHistoryResponse, error)
	mustEmbedUnimplementedTelemetryServiceServer()
}

// UnimplementedTelemetryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTelemetryServiceServer struct {
}

func (UnimplementedTelemetryServiceServer) IngestTelemetry(TelemetryService_IngestTelemetryServer) error {
	return status.Errorf(codes.Unimplemented, "method IngestTelemetry not implemented")
}
func (UnimplementedTelemetryServiceServer) GetTelemetryHistory(context.Context, *TelemetryHistoryRequest) (*TelemetryHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTelemetryHistory not implemented")
}
func (UnimplementedTelemetryServiceServer) mustEmbedUnimplementedTelemetryServiceServer() {}

// UnsafeTelemetryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelemetryServiceServer will
// result in compilation errors.
type UnsafeTelemetryServiceServer interface {
	mustEmbedUnimplementedTelemetryServiceServer()
}

func RegisterTelemetryServiceServer(s grpc.ServiceRegistrar, srv TelemetryServiceServer) {
	s.RegisterService(&TelemetryService_ServiceDesc, srv)
}

func _TelemetryService_IngestTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TelemetryServiceServer).IngestTelemetry(&telemetryServiceIngestTelemetryServer{ServerStream: stream})
}

type TelemetryService_IngestTelemetryServer interface {
	SendAndClose(*IngestSummary) error
	Recv() (*TelemetryReading, error)
	grpc.ServerStream
}

type telemetryServiceIngestTelemetryServer struct {
	grpc.ServerStream
}

func (x *telemetryServiceIngestTelemetryServer) SendAndClose(m *IngestSummary) error {
	return x.ServerStream.SendMsg(m)
}

func (x *telemetryServiceIngestTelemetryServer) Recv() (*TelemetryReading, error) {
	m := new(TelemetryReading)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TelemetryService_GetTelemetryHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TelemetryHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).GetTelemetryHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryService_GetTelemetryHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).GetTelemetryHistory(ctx, req.(*TelemetryHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TelemetryService_ServiceDesc is the grpc.ServiceDesc for TelemetryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelemetryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telemetry.TelemetryService",
	HandlerType: (*TelemetryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTelemetryHistory",
			Handler:    _TelemetryService_GetTelemetryHistory_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "IngestTelemetry",
			Handler:       _TelemetryService_IngestTelemetry_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "telemetry.proto",
}
